$ErrorActionPreference = "Stop"

$projectDirectory = Split-Path -Parent $PSScriptRoot
$assetsDirectory = Join-Path $projectDirectory "assets"
$outputFile = Join-Path $assetsDirectory "default-assets.js"

$assets = [ordered]@{
  background = @{ File = "background_1.jpg"; Mime = "image/jpeg" }
  bismillah = @{ File = "bismi_1.svg"; Mime = "image/svg+xml" }
  logo       = @{ File = "logo_maldives.png"; Mime = "image/png" }
}

$lines = @(
  "// Generated by tools/embed-default-assets.ps1. Do not edit this file manually."
  "window.DEFAULT_POSTER_ASSETS = Object.freeze({"
)

foreach ($name in $assets.Keys) {
  $asset = $assets[$name]
  $path = Join-Path $assetsDirectory $asset.File

  if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
    throw "Missing bundled asset: $path"
  }

  $base64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($path))
  $lines += "  ${name}: `"data:$($asset.Mime);base64,$base64`","
}

$lines += "});"
[IO.File]::WriteAllLines($outputFile, $lines, [Text.UTF8Encoding]::new($false))

Write-Host "Embedded default poster artwork in $outputFile"
